name: Build artifact
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: kohlerdominik/docker-run-action@v2
      with:
        image: biohackrxiv/bhxiv-gen-pdf:master
        volumes: ${{ github.workspace }}:/work
        workdir: /work
        run: |
          echo "Running Script"
          gen-pdf paper
    - name: Create info file
      run: |
         echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
         > info.txt
    - name: Update latest release
      uses: pyTooling/Actions/releaser@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          paper.pdf
          info.txt
